name: Build guides sln

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/all-guides-sln.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/all-guides-sln.yml'
  schedule:
    - cron: '0 0 * * 0' # Once a week: "At 00:00 on Sunday."

defaults:
  run:
    shell: pwsh

env:
  SLN_FILEPATH : ${{github.workspace}}/DotNet.Guides.slnx

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.x
    - name: Clears local NuGet resources
      if: matrix.os == 'windows-latest' # required due to bug when using dotnet cli on windows-latest. See https://github.com/dotnet/core/issues/5881 and https://github.com/actions/setup-dotnet/issues/155
      run: dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore ${{env.SLN_FILEPATH}}
    - name: Build
      run: dotnet build ${{env.SLN_FILEPATH}} -c Release --no-restore